"""Anthropic Claude AI service — replaces Gemini for all LLM queries."""

import asyncio
import ssl
from typing import AsyncGenerator

# Use the Windows native certificate store so corporate proxy CAs are trusted
try:
    import truststore
    truststore.inject_into_ssl()
except Exception:
    pass

import anthropic
from loguru import logger

from app.core.config import get_settings
from app.core.cache import cache

settings = get_settings()

_MODEL = "claude-haiku-4-5-20251001"
_CLIENT: anthropic.Anthropic | None = None
_ASYNC_CLIENT: anthropic.AsyncAnthropic | None = None


def _get_client() -> anthropic.Anthropic | None:
    global _CLIENT
    if _CLIENT is None and settings.anthropic_api_key:
        try:
            _CLIENT = anthropic.Anthropic(api_key=settings.anthropic_api_key)
            logger.info("Anthropic Claude client initialized (model: {})", _MODEL)
        except Exception as exc:
            logger.warning("Failed to initialize Anthropic client: {}", exc)
    return _CLIENT


def _get_async_client() -> anthropic.AsyncAnthropic | None:
    global _ASYNC_CLIENT
    if _ASYNC_CLIENT is None and settings.anthropic_api_key:
        try:
            _ASYNC_CLIENT = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)
        except Exception as exc:
            logger.warning("Failed to initialize async Anthropic client: {}", exc)
    return _ASYNC_CLIENT


def query_claude(user_query: str) -> dict:
    """Synchronous Claude query with in-memory cache."""
    client = _get_client()
    if client is None:
        return {
            "result": "AI analysis unavailable — ANTHROPIC_API_KEY not configured.",
            "cached": False,
            "confidence": 0.0,
        }

    try:
        cached = cache.get(user_query)
        if cached:
            return {"result": cached, "cached": True}
    except Exception:
        pass

    message = client.messages.create(
        model=_MODEL,
        max_tokens=1024,
        messages=[{"role": "user", "content": user_query}],
    )
    result = message.content[0].text

    try:
        cache.set(user_query, result, ex=3600)
    except Exception:
        pass

    return {
        "result": result,
        "explanation": "Generated by Claude AI (Anthropic) based on financial data and market analysis",
        "confidence": 0.88,
    }


async def stream_claude(user_query: str) -> AsyncGenerator[dict, None]:
    """Async generator that streams Claude responses chunk by chunk."""
    async_client = _get_async_client()
    if async_client is None:
        yield {"error": "ANTHROPIC_API_KEY not configured"}
        return

    try:
        async with async_client.messages.stream(
            model=_MODEL,
            max_tokens=1024,
            messages=[{"role": "user", "content": user_query}],
        ) as stream:
            async for text in stream.text_stream:
                if text:
                    yield {"response": text}
                await asyncio.sleep(0)
    except Exception as exc:
        logger.error("Claude stream error: {}", exc)
        yield {"error": str(exc)}
