import asyncio
from typing import AsyncGenerator
from google import genai
from app.core.config import get_settings
from app.core.cache import cache

settings = get_settings()

# Initialize the Gemini client once at module level
_GEMINI_CLIENT = genai.Client(api_key=settings.gemini_api_key)
_GEMINI_MODEL = "gemini-1.5-flash"


def query_gemini(user_query: str):
    # Check cache (graceful fallback if Redis is unavailable)
    try:
        cached = cache.get(user_query)
        if cached:
            return {"result": cached, "cached": True}
    except Exception:
        pass

    # Use Gemini SDK for querying
    response = _GEMINI_CLIENT.models.generate_content(
        model=_GEMINI_MODEL,
        contents=user_query,
    )
    result = response.text if hasattr(response, "text") else str(response)

    # Store in cache (1 hour expiry) — ignore failures
    try:
        cache.set(user_query, result, ex=3600)
    except Exception:
        pass

    return {
        "result": result,
        "explanation": "Generated by Gemini AI based on financial data and sentiment analysis",
        "confidence": 0.85
    }


async def stream_gemini(user_query: str) -> AsyncGenerator[dict, None]:
    """
    Async generator that streams Gemini responses using the official SDK.
    """
    for chunk in _GEMINI_CLIENT.models.generate_content_stream(
        model=_GEMINI_MODEL,
        contents=user_query,
    ):
        if hasattr(chunk, "text") and chunk.text:
            yield {"response": chunk.text}
        await asyncio.sleep(0)  # allow event loop to switch
