import requests
from app.core.config import get_settings
from app.core.cache import cache

settings = get_settings()
GEMINI_URL = "https://api.gemini.com/v1/query"

def query_gemini(user_query: str):
    # Check cache
    cached = cache.get(user_query)
    if cached:
        return {"result": cached, "cached": True}

    # Call Gemini API
    response = requests.post(
        GEMINI_URL,
        headers={"Authorization": f"Bearer {settings.gemini_api_key}"},
        json={"input": user_query}
    )

    result = response.json()

    # Store in cache (1 hour expiry)
    cache.set(user_query, str(result), ex=3600)

    # Add explainability wrapper
    return {
        "result": result,
        "explanation": "Generated by Gemini AI based on financial data and sentiment analysis",
        "confidence": 0.85
    }
