import asyncio
from typing import AsyncGenerator, Optional
from loguru import logger
from app.core.config import get_settings
from app.core.cache import cache

settings = get_settings()

_GEMINI_MODEL = "gemini-1.5-flash"
_GEMINI_CLIENT = None

if settings.gemini_api_key:
    try:
        from google import genai
        _GEMINI_CLIENT = genai.Client(api_key=settings.gemini_api_key)
        logger.info("Gemini client initialized (model: {})", _GEMINI_MODEL)
    except Exception as exc:
        logger.warning("Failed to initialize Gemini client: {}", exc)


def query_gemini(user_query: str) -> dict:
    """Synchronous Gemini query with Redis cache fallback."""
    if _GEMINI_CLIENT is None:
        return {
            "result": "AI analysis unavailable — GEMINI_API_KEY not configured.",
            "cached": False,
            "confidence": 0.0,
        }

    try:
        cached = cache.get(user_query)
        if cached:
            return {"result": cached, "cached": True}
    except Exception:
        pass

    response = _GEMINI_CLIENT.models.generate_content(
        model=_GEMINI_MODEL,
        contents=user_query,
    )
    result = response.text if hasattr(response, "text") else str(response)

    try:
        cache.set(user_query, result, ex=3600)
    except Exception:
        pass

    return {
        "result": result,
        "explanation": "Generated by Gemini AI based on financial data and sentiment analysis",
        "confidence": 0.85,
    }


async def stream_gemini(user_query: str) -> AsyncGenerator[dict, None]:
    """Async generator that streams Gemini responses chunk by chunk."""
    if _GEMINI_CLIENT is None:
        yield {"error": "GEMINI_API_KEY not configured"}
        return

    try:
        for chunk in _GEMINI_CLIENT.models.generate_content_stream(
            model=_GEMINI_MODEL,
            contents=user_query,
        ):
            if hasattr(chunk, "text") and chunk.text:
                yield {"response": chunk.text}
            await asyncio.sleep(0)
    except Exception as e:
        yield {"error": str(e)}
