"""Add wallet and portfolio enhancements

Revision ID: bc06f0c36814
Revises: 33d2e3bd5f84
Create Date: 2026-03-07 11:30:46.350652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc06f0c36814'
down_revision = '33d2e3bd5f84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create ENUM types manually
    op.execute("CREATE TYPE transactiontype AS ENUM ('DEPOSIT', 'WITHDRAW', 'TRADE_BUY', 'TRADE_SELL', 'DIVIDEND', 'FEE')")
    op.execute("CREATE TYPE transactionstatus AS ENUM ('PENDING', 'COMPLETED', 'FAILED')")
    
    # Create wallets table
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False, server_default='0.0'),
    sa.Column('total_deposited', sa.Float(), nullable=False, server_default='0.0'),
    sa.Column('total_withdrawn', sa.Float(), nullable=False, server_default='0.0'),
    sa.Column('total_invested', sa.Float(), nullable=False, server_default='0.0'),
    sa.Column('currency', sa.String(length=10), nullable=False, server_default='USD'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    
    # Create wallet_transactions table
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_before', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    
    # Portfolio transactions table
    op.create_table('portfolio_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_transactions_id'), 'portfolio_transactions', ['id'], unique=False)
    
    # Add columns to existing tables
    op.add_column('portfolio_holdings', sa.Column('sector', sa.String(length=50), nullable=True))
    op.add_column('portfolios', sa.Column('invested_amount', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('portfolios', sa.Column('risk_profile', sa.String(length=20), nullable=False, server_default='moderate'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'risk_profile')
    op.drop_column('portfolios', 'invested_amount')
    op.drop_column('portfolio_holdings', 'sector')
    op.drop_index(op.f('ix_portfolio_transactions_id'), table_name='portfolio_transactions')
    op.drop_table('portfolio_transactions')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    # Drop ENUM types
    op.execute("DROP TYPE IF EXISTS transactionstatus")
    op.execute("DROP TYPE IF EXISTS transactiontype")
    # ### end Alembic commands ###
